export default {
  // main
  mainEmailBool: false,
  mainNicknameBool: false,
  mainIsSignIn: false,
  // user 정보
  userInfo: null,
  // profile
  profileNicknameBool: false,
  profileConsultantProfile: [],
  profileConsultantLike: [],
  profileHistoryConfession: [],
  profileHistoryAdvice: [],
  profileHistoryReceivedReview: [],
  profileHistoryWrittenReview: [],
  profileHistoryCommunity: [],
  profileHistoryComment: [],
  // confession
  confessionLastPageNum: 0,
  confessionMeetingList: [],
  confessionReviewList: [],
  // advice
  adviceConsultantList: [],
  adviceLastPageNum: 0,
  adviceRankList: [],
  // community
  communityList: [],
  communityLastPageNum: 0,
  communityDetail: [],
  communityComment: [],
  // chatRoom
  chatRoomList: [],
  chatRoomId: [],
  chatRoomMessage: [],
  chatRoomUserList: [],
  meetingIsActive: false,
  // meeting
  adviceMeetingInfo: [],
  confessionMeetingInfo: [],
  meetingParticipantLimit: true,
  // notice
  noticeLastPageNum: 0,
  noticeList: [],
  noticeDetail: [],
  // qna
  qnaLastPageNum: 0,
  qnaList: [],
  qnaDetail: [],
  qnaAnswerList: [],
}
