export default {
  isLogin: false,
  isLoginError: false,
  userInfo: null,
  user_id: null,
  email_bool: false,
  nickname_bool: false,
  pro_nickname_bool: false,
  profileConsultant: [],
  adviceRank: [],
  adviceView: [],
  adviceTotalPageNum: [],
  advicePageNum: 1,
  communityView: [],
  communityDetail: [],
  communityLike: [],
  communityComment: [],
  chatRoomList: [],
};
